---
# Install grafana agents
- name: "Ensure o11y can be enabled in this host"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "o11y is not supported in this host"
    that:
      - (group_names|intersect(o11y_enabled_roles)|length>0)
  when: o11y_enable

- name: Agent directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: "{{ 'directory' if o11y_enable else 'absent' }}"
    mode: 0755
  loop: "{{ o11y_grafana_agent_dirs }}"

- name: Install unzip
  ansible.builtin.apt:
    name: unzip
    state: "present"

- name: Download and unzip grafana agent
  ansible.builtin.unarchive:
    src: "{{ grafana_agent_pkg }}"
    dest: "{{ o11y_grafana_agent_dir }}"
    remote_src: true
  when: o11y_enable

- name: Make agent executable
  ansible.builtin.file:
    path: "{{ o11y_grafana_agent_dir }}/grafana-agent-linux-{{ ubuntu_arch }}"
    mode: "a+x"
  when: o11y_enable

- name: Creating a service file
  ansible.builtin.copy:
    dest: "{{ o11y_grafana_agent_unit }}"
    mode: 0644
    content: |
      [Unit]
      Description=Grafana-agent Service
      Requires=network.target
      After=network.target
      [Service]
      Type=simple
      ExecStart={{ o11y_grafana_agent_dir }}/grafana-agent-linux-{{ ubuntu_arch }} -config.file={{ o11y_grafana_agent_dir }}/agent.yaml
      Restart=on-abnormal
      [Install]
      WantedBy=multi-user.target
  when: o11y_enable

- name: Agent configuration
  ansible.builtin.template:
    src: "grafana-agent.yaml.j2"
    dest: "{{ o11y_grafana_agent_dir }}/agent.yaml"
    mode: 0644
  when: o11y_enable and maas_version is version("3.5",'<')
  notify:
    - "Start grafana agent"

- name: Agent configuration for MAAS 3.5
  ansible.builtin.template:
    src: "agent-{{ maas_installation_type }}.yaml.j2"
    dest: "{{ o11y_grafana_agent_dir }}/agent.yaml"
    mode: 0644
  when: o11y_enable and maas_version is version("3.5",'>=')
  notify:
    - "Start grafana agent"
