# MAAS installation setup
maas_version: "latest"          # ie: 3.2, 2.8
maas_installation_type: "snap"  # snap or deb
maas_snap_channel: "stable"     # if using snap, then the channel. ie: stable, beta, edge
maas_deb_state: "present"       # if using deb, the state for install
install_metrics: true           # install metrics for the MAAS

# administrator account details
admin_username: "admin"
admin_password: "admin"
admin_email: "admin@email.com"
admin_id: "admin"
