---

- name: Install MAAS - Snap
  community.general.snap:
    name: maas
    channel: '{{ maas_use_version }}/{{ maas_snap_channel }}'
  when: (maas_installation_type|lower == 'snap') and ('maas_region_controller' not in group_names)

- name: Add MAAS apt Respository
  ansible.builtin.apt_repository:
    repo: "ppa:maas/{{ maas_use_version }}"
  when: (maas_installation_type|lower == 'deb') and ('maas_region_controller' not in group_names)

- name: Create MAAS Unix Group
  ansible.builtin.group:
    name: maas
    state: present

- name: Create MAAS Unix User
  ansible.builtin.user:
    name: maas
    group: maas
    state: present

- name: Install Deb Dependancy
  ansible.builtin.apt:
    name: chrony
    state: present
  when: (maas_installation_type | lower == 'deb')

- name: Install MAAS Rack Controller
  ansible.builtin.apt:
    name: maas-rack-controller
    state: "{{ maas_deb_state | default('present') }}"
  when: (maas_installation_type | lower == 'deb')

- name: Initialise MAAS Rack Controller
  ansible.builtin.command: maas init --mode=rack --maas-url={{ maas_url }} --secret={{ maas_rack_secret }}
  when: (maas_installation_type | lower == 'snap') and ('maas_region_controller' not in group_names)

- name: Initialise MAAS Rack Controller
  ansible.builtin.command: maas-rack register --url={{ maas_url }} --secret={{ maas_rack_secret }}
  when: (maas_installation_type | lower == 'deb')

- name: Enable TLS
  ansible.builtin.include_role:
    name: common
    tasks_from: TLS
  # TLS is available only in MAAS 3.2 or higher
  when: maas_use_version is version("3.2", '>=') and enable_tls

- name: Create metrics file
  ansible.builtin.file:
    path: "{{ maas_installmetric_file }}"
    state: touch
    mode: 0644
  when: install_metrics
