---

- name: Uninstall MAAS - snap
  community.general.snap:
    name: maas
    state: absent
  when: (maas_installation_type|lower == 'snap')

- name: Uninstall MAAS - deb
  ansible.builtin.apt:
    name: maas_rack_controller
    state: absent
  when: (maas_installation_type|lower == 'deb')


- name: Uninstall MAAS Deb Dependancy
  ansible.builtin.apt:
    name: chrony
    state: absent
  when: (maas_installation_type|lower == 'deb')