---
- name: Update MAAS - Snap
  ansible.builtin.command: snap refresh --channel={{ maas_use_version }}/{{ maas_snap_channel }} maas
  when: maas_installation_type | lower == 'snap'

- name: Add MAAS apt Repository
  ansible.builtin.apt_repository:
    repo: "ppa:maas/{{ maas_use_version }}"
  when: maas_installation_type | lower == 'deb'

- name: Install Deb Dependency
  ansible.builtin.apt:
    name: chrony
    state: latest
  when: (maas_installation_type | lower == 'deb')

- name: Install MAAS Rack Controller
  ansible.builtin.apt:
    name: "maas-rack-controller"
    state: latest
    update_cache: true
  when: (maas_installation_type | lower == 'deb')
