---
- name: Display choices
  ansible.builtin.debug:
    msg: 'Upgrading MAAS {{ maas_installation_type }} V. {{ maas_version }} on {{ ansible_facts["distribution"] }}'

- name: Update MAAS snap
  ansible.builtin.command: snap refresh --channel={{ maas_version }} maas
  when: maas_installation_type|lower == 'snap'

- name: Install deb dependencies
  ansible.builtin.apt:
    name: "maas-rack-controller"
    state: latest
    update_cache: yes
  when: maas_installation_type|lower == 'deb' and ('maas_region_controller' not in role_names)
