---
- name: Update MAAS - Snap
  ansible.builtin.command: snap refresh --channel={{ maas_use_version }} maas
  when: maas_installation_type | lower == 'snap'

- name: Add MAAS apt Respository
  ansible.builtin.apt_repository:
    repo: "ppa:maas/{{ maas_use_version }}"
  when: maas_installation_type | lower == 'deb'

- name: Install Deb Dependancy
  ansible.builtin.apt:
    name: chrony
    state: latest
  when: (maas_installation_type | lower == 'deb')

- name: Install MAAS Rack Controller
  ansible.builtin.apt:
    name: "maas-rack-controller"
    state: latest
    update_cache: yes
  when: (maas_installation_type | lower == 'deb')
