---
- name: "Uninstall HAProxy"
  ansible.builtin.apt:
    name: "haproxy"
    state: absent
    update_cache: true

- name: "Remove HAProxy Config"
  ansible.builtin.file:
    path: /etc/haproxy/haproxy.cfg
    state: 'absent'
