---
- name: Restore Database
  community.postgresql.postgresql_db:
    name: "{{ maas_postgres_database }}"
    state: restore
    target: "{{ maas_postgres_backup_path }}"
  become: true
  become_user: postgres
  when: is_current_postgres_primary|bool
