---
- name: Set postgres number for uninstall
  ansible.builtin.set_fact:
    maas_postgres_version_number: "{{ 14 if ansible_distribution_major_version|float >= 22 and maas_use_version is version('3.2', '>') else 12 }}"

- name: Setting config dirs for uninstall
  ansible.builtin.set_fact:
    maas_postgres_config_dir: "/etc/postgresql/{{ maas_postgres_version_number }}/main/"

- name: "Uninstall Postgres"
  ansible.builtin.apt:
    name: "{{ maas_postgres_deb_name | default('postgresql-{{ maas_postgres_version_number }}') }}"
    state: absent
    purge: true

- name: "Uninstall libpq-dev"
  ansible.builtin.apt:
    name: libpq-dev
    state: absent

- name: "Uninstall acl"
  ansible.builtin.apt:
    name: acl
    state: absent

- name: "Uninstall psycopg2"
  ansible.builtin.pip:
    name: "psycopg2"
    state: absent
  failed_when: false
