---
- name: Set postgres number for uninstall
  ansible.builtin.set_fact:
    maas_postgres_version_number: "{{ 14 if ansible_facts.distribution_release == 'jammy' and maas_version|float > 3.2 else 12 }}"

- name: Setting config dirs for uninstall
  ansible.builtin.set_fact:
    maas_postgres_config_dir: "/etc/postgresql/{{ maas_postgres_version_number }}"

- name: "Uninstall Postgres"
  ansible.builtin.apt:
    name: "{{ maas_postgres_deb_name | default('postgresql-{{ maas_postgres_version_number }}') }}"
    state: absent

- name: "Uninstall libpq-dev"
  ansible.builtin.apt:
    name: libpq-dev
    state: absent

- name: "Uninstall acl"
  ansible.builtin.apt:
    name: acl
    state: absent

- name: "Uninstall psycopg2"
  ansible.builtin.pip:
    name: "psycopg2"
    state: absent
  ignore_errors: true

- name: Delete Files"
  file:
    state: 'absent'
    path: "{{ item }}"
  with_items:
    - "{{ maas_postgres_config_dir }}"
    - "write_postgres_config.yaml"
