---
- name: "Uninstall Pacemaker Packages"
  ansible.builtin.apt:
    name:
      - pacemaker
      - pacemaker-common
      - pcs
      - fence-agents
      - resource-agents-paf
      - fence-virtd
      - fence-virt
    state: absent
    purge: true
    autoremove: true

- name: "Remove Pacemaker artifacts"
  ansible.builtin.file:
    state: absent
    name: "{{ item }}"
  with_items:
    - /tmp/configure_fencing.sh
    - /tmp/configure_pacemaker.sh
    - /tmp/pacemaker_status
    - /tmp/pacemaker_auth
    - /tmp/stonith_cfg
    - /etc/cluster
    - /etc/tmpfiles.d/postgresql-part.conf
    - /etc/ssh/sshd_config.d/pacemaker_sshd.conf
